autodiscovery: "329718"
clientId: "822f5dca377640c59acc400ec2131bea"
clientSecret: "![FWXWbkslWYAugZ5+g/VWpbGT958iJX3UQngG6GRsJFl7fKHrZugQb2gReV5gMnCn]"
https:
  host: "0.0.0.0"
  port: "8082"
  keystore:
    type: "JKS"
    path: "keystore-servier-mule-cloudhub.jks"
    alias: "servier-mule-cloudhub"
    password: "![PthF7l54d4YEsOQZlz1JTKHgbzAPygqVjYAYLoZ6tAw=]"
    keypassword: "![yj8ixvywJqQfxdfv9ATWf0245NpIIH5CfOZxAywmomM=]"
salesforce:
  clientId: "3MVG96_7YM2sI9wSB4dUunaLEZxq39YqHrglcHg7S0z_ttWWZSBQei3.o5Yuhpn2i_MA_ethoJjvKJ4ijb5Dc"
  clientSecret: "![Wxr9o3wpD41UZn8qKdMpBUur1PIlQ5oVbiNXbfdsOwPXjRWDyMC5bqHJ/EhfwutVP/9WnEOxsu10Tp1uAt1R2dXf0AkZhgb6zQ57XpYUIAY=]"
  username: "mulesoft.integration@servier.com.federates"
  password: "![vm8NRfA9OP0yNFD6tSJaLpWkpCc7B0R8k0OSuTo+WLw=]"
  token: "![qF6vieRigkdhmu9XGeNclsng2/3Y+qmCTCz+R5HKyrU=]"
  tokenendpoint: "https://servier-federates.my.salesforce.com/services/oauth2/token"
  environment-domain: "@servier.com"
services:
  trial:
    host: "mule-worker-internal-servier-trialtrove-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  scrip:
    host: "mule-worker-internal-servier-scrip-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  dbs:
    host: "mule-worker-internal-servier-dbs-process-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    responsetimeout: "7200000" # two hours
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  pubmed:
    host: "mule-worker-internal-servier-pubmed-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  pubchem:
    host: "mule-worker-internal-servier-pubchem-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  chembl:
    host: "mule-worker-internal-servier-chembl-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  herokuapi:
    host: "mule-worker-internal-servier-heroku-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  uniprot:
    host: "mule-worker-internal-servier-uniprot-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  kegg:
    host: "mule-worker-internal-servier-kegg-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
  pharmaprojects:
    host: "mule-worker-internal-servier-pharma-projects-sys-api.de-c1.eu1.cloudhub.io"
    port: "8092"
    basepath: "/api"
    protocol: "HTTPS"
    truststore:
      type: "JKS"
      path: "truststore-servier-mule.jks"
      password: "![u1hy/a/lw4E53YT99421mB1/TbpGpae4cYhQz4tWIfQ=]"
jobs:
  maxrecordsperbatch: "10000"
  maxjobinfopollingiterations: "200"
  milisecondsbetweenjobinfopollingiterations: "10000"
